# Generated by Django 5.0.6 on 2024-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(default='agent007', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
